// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgglgxogvxpxqfwaqpbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnZ2xneG9ndnhweHFmd2FxcGJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDI4ODIsImV4cCI6MjA3NDA3ODg4Mn0.2By2XiKPaQhEwlLBr_BWardt_giKAvZThRJigdTCeio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});