// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnngnhnvnexzrsrmurpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBubmduaG52bmV4enJzcm11cnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTQ5NjEsImV4cCI6MjA3NDI5MDk2MX0.J8j0YLm_5Y51Yc-Woj7aGFe3TQIHD_EEJ8oYKoGtgxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});